services:
  pg_normalized:
    build: services/pg_normalized
    volumes:
      - ./:/tmp/db
      - pg_normalized:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 24528:5432
  web:
    build: services/web
    depends_on:
      - pg_normalized
    expose:
      - 5000
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=pass
      - PG_HOST=pg_normalized
      - PG_PORT=5432
    volumes:
      - ./services/web:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
  nginx:
    build: ./services/nginx
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
    ports:
      - 1087:80
    depends_on:
      - web 

volumes:
  pg_normalized:
  static_volume:
